Include the check-task-migration-md check
In build-definitions repo, this was a separate step run in konflux on
PRs, see https://github.com/konflux-ci/build-definitions/blob/e3ddb9e8db62dd41870e5b076e8fb738735d7be3/.tekton/pull-request.yaml#L260-L285

STONEBLD-3753

Signed-off-by: mkosiarc <mkosiarc@redhat.com>

diff --git a/{{cookiecutter.repo_root}}/.github/workflows/check-task-migration.yaml b/{{cookiecutter.repo_root}}/.github/workflows/check-task-migration.yaml
--- a/{{cookiecutter.repo_root}}/.github/workflows/check-task-migration.yaml
+++ b/{{cookiecutter.repo_root}}/.github/workflows/check-task-migration.yaml
@@ -42,3 +42,19 @@ jobs:
           git checkout -b pr-verify
           export IN_CLUSTER=1
           bash ./hack/validate-migration.sh
+
+      - name: Check MIGRATION.md
+        run: |
+          EXIT=0
+          for TASK_DIR in $(ls task); do
+            # Do not check on initial version of task
+            for VERSION in $(ls -d task/$TASK_DIR/*/ | sort --version-sort | tail -n+2); do
+              MIGRATION_FILE=${VERSION}MIGRATION.md
+              if [ ! -f $MIGRATION_FILE ]; then
+                 echo "Missing file $MIGRATION_FILE"
+                 EXIT=1
+              fi
+            done
+          done
+          exit $EXIT
+
