renovate-ignore-shared-ci: handle all config paths
Don't require the repo to have exactly renovate.json, support all the
paths documented in https://docs.renovatebot.com/configuration-options/

This does not mean we support JSON5 syntax, we still support only
regular JSON. But the file extension doesn't have much impact on that
(Renovate handles JSON5 in .json files), so let's just look through all
the paths and hope for the best.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

diff --git a/{{cookiecutter.repo_root}}/.github/workflows/update-shared-ci.yaml b/{{cookiecutter.repo_root}}/.github/workflows/update-shared-ci.yaml
--- a/{{cookiecutter.repo_root}}/.github/workflows/update-shared-ci.yaml
+++ b/{{cookiecutter.repo_root}}/.github/workflows/update-shared-ci.yaml
@@ -58,8 +58,30 @@ jobs:
             echo draft=false >> "$GITHUB_OUTPUT"
           fi
 
-          if [[ ! -e renovate.json ]]; then
-            echo "renovate.json doesn't exist, skipping update" >&2
+          renovate_config_exists() {
+            # https://docs.renovatebot.com/configuration-options/
+            local renovate_config_paths=(
+              renovate.json
+              renovate.json5
+              .github/renovate.json
+              .github/renovate.json5
+              .gitlab/renovate.json
+              .gitlab/renovate.json5
+              .renovaterc
+              .renovaterc.json
+              .renovaterc.json5
+            )
+
+            for file in "${renovate_config_paths[@]}"; do
+              if [[ -e "$file" ]]; then
+                return 0
+              fi
+            done
+
+            return 1
+          }
+          if ! renovate_config_exists; then
+            echo "Renovate config file not found, skipping update" >&2
             exit
           fi
 
