update-shared-ci: run renovate-ignore script
While updating the shared CI, run the renovate-ignore script in case the
update brings in new workflow files. That way, the new workflows will be
automatically added to renovate.json.

Corner case: if the update causes a merge conflict with the
renovate-ignore script, don't run the script and mention the problem in
the PR description.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

diff --git a/.github/workflows/update-shared-ci.yaml b/.github/workflows/update-shared-ci.yaml
--- a/.github/workflows/update-shared-ci.yaml
+++ b/.github/workflows/update-shared-ci.yaml
@@ -58,6 +58,29 @@ jobs:
             echo draft=false >> "$GITHUB_OUTPUT"
           fi
 
+          if [[ ! -e renovate.json ]]; then
+            echo "renovate.json doesn't exist, skipping update" >&2
+            exit
+          fi
+
+          renovate_update_script=hack/renovate-ignore-shared-ci.sh
+
+          for conflict in "${merge_conflicts[@]}" "${rejected_patches[@]}"; do
+            if [[ "$conflict" == "$renovate_update_script" ]]; then
+              cat << EOF >> /tmp/body.md
+
+          > [!WARNING]
+          >
+          > \`$renovate_update_script\` has a merge conflict, the workflow couldn't run it.
+          > After resolving the conflict, please run the script manually.
+          EOF
+              echo "cannot run $renovate_update_script due to merge conflict, skipping" >&2
+              exit
+            fi
+          done
+
+          bash "$renovate_update_script"
+
       - uses: actions/create-github-app-token@v2.0.6
         id: app-token
         with:
